apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meridian-frontend
  labels:
    cloud.googleapis.com/location: asia-southeast1
spec:
  template:
    spec:
      containers:
        - image: gcr.io/smart-meeting-scheduler-492310/meridian-frontend # Change this to your Project ID
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://meridian-backend-REPLACE_ME.a.run.app" # You'll update this after deploying backend